ny_data:
  target: dev
  outputs:
    dev:
      type: redshift
      host: mage-redshift-cluster-1.cqg6q1mpcfl7.eu-north-1.redshift.amazonaws.com
      user: mrken
      password: Mrken2172
      dbname: dev
      schema: analytics
      port: 5439
